const actionTypes = {
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_GENRES: "FETCH_GENRES",
    FETCH_SORT_BY_LIST: "FETCH_SORT_BY_LIST",
    FETCH_MOVIE_BY_ID: "FETCH_MOVIE_BY_ID",
    
    SELECT_MOVIE: "SELECT_MOVIE",
    SELECT_SEARCH: "SELECT_SEARCH",
    SELECT_SORTED_BY: "SELECT_SORTED_BY",
    SELECT_EDIT_MOVIE: "SELECT_EDIT_MOVIE",

    EDIT_MOVIE: "EDIT_MOVIE",
    ADD_MOVIE: "ADD_MOVIE",
    DELETE_MOVIE: "DELETE_MOVIE",

    SORT_MOVIES: "SORT_MOVIES",
    
    FILTER_MOVIES: "FILTER_MOVIES",
    SET_FILTER_BY: "SET_FILTER_BY",
  };
  
  export default actionTypes;